services:
  app:
    image: ghcr.io/e4ld3rs0n/archeo:latest
    container_name: archeo-app
    ports:
      - "8678:8000"
    env_file:
      - stack.env
    volumes:
      - /docker/archeo/uploads:/app/static/uploads
    depends_on:
      - db
    command: ["dockerize", "-wait", "tcp://db:5432", "-timeout", "30s", "gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "--timeout", "120", "main:app"]

  db:
    image: postgres:16
    container_name: archeo-db
    environment:
      POSTGRES_DB: ${DB_NAME}             
      POSTGRES_USER: ${DB_USER}         
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
    volumes:
      - /docker/archeo/dbdata:/var/lib/postgresql/data
