name: Build and Push Docker image to GHCR

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  # Build & push only the “latest” tag on commits to main
  build-latest:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code  
        uses: actions/checkout@v4

      - name: Set up Docker Buildx  
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR  
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push “latest”  
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

  # Build & push both the versioned tag and “latest” on tag‐pushes
  build-tag:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code  
        uses: actions/checkout@v4

      - name: Set up Docker Buildx  
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR  
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push versioned image  
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:latest
